### ISSUE TITLE
[各種情報設定]管理者権限の実装

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#10]
管理者権限機能の実装をする。
管理者権限を持つものはユーザー情報設定画面で自社情報の登録・更新、会社ロゴの設定等ができるようになる。

**Comment by gamasenninn** [comment]
ログイン画面はこんな感じでいちおうcompleteにしておく。
ユーザごとの権限設定はAPI作成時に行うことにする。
