### ISSUE TITLE
設定画面の印鑑・ロゴアップロード機能を実装する

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#213]
現時点で設定画面の印鑑・ロゴアップロード機能は実装してないので、実装する。
印鑑・ロゴの表示部分もフェイクなので、実装する。

**Comment by gamasenninn** [comment]
アップロード機能クラス化するので、ちょっと待ってね。
ロゴとか印鑑とかのアセットをどこに置くか、迷っている。どうしたものかね？
請求書などのアップロードファイルの置き場所も同時に検討したい。どうしたものかね？
