### ISSUE TITLE
初期DBデータをCSVでまとめて流す機能を入れる

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#228]
別の請求・見積書作成ソフトからSohoCaddieに移管する際にデータを丸々インポートできるようにCSVインポート機能を作成する。

**Comment by gamasenninn** [comment]
この機能は汎用性をもたせたほうがいいかもな。
・どのテーブルにインポートするか
・どの項目をインポートするか
などをJsonもしくはyamlに書いてあげると、それの仕様にしたがってインポートするみたいな感じ。

**Comment by monomonosu** [comment]
ツッコミどころは多いが、とりあえず完了。
