### ISSUE TITLE
APIに追加が何件かあるのでテストを書く

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#245]
そういえばテストを書いてないのでテストを書かなければ

**Comment by gamasenninn** [comment]
ついでにいうと、いまのテストはxxx_test.pyになってるよね。これだと python -m unittest　で一括テストができないので、test_xxx.pyという感じでファイル名を替えておいたほうがよい。

**Comment by gamasenninn** [comment]
さらに、ついでにいうと。モデルレベルのテストプログラムはあるけど、APIレベルのテストはないよ。

**Comment by monomonosu** [comment]
確かにその通りだ。
修正しちゃうね

**Comment by monomonosu** [comment]
元々あったユニットテストのファイル名変更。変更のあったカラムの修正を行った。
後で追加されたモデルのテストはこれから着手。
