### ISSUE TITLE
請求書・見積書ページもルートパラメータでページ切り替え可能にする。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#259]
とても複雑なので別Issueを立てた。
以下のページをVueRouterを使用し、ルートパラメータでページ切り替えできるようにする。

- [x] invoice.html
- [x] invoice_dust.html
- [x] quotation.html
- [x] quotation_dust.html

dustページは更新ボタンを押してしまうとindexページに飛んでしまうのでその修正。

**Comment by gamasenninn** [comment]
このタスクについては、getInvoices()でなく、なるべくgetInvoice()のままでいきたいと思っている。そのためにはthis.invoiceをローカルにストアし、レストア時にマッピングする必要ありかな。

**Comment by gamasenninn** [comment]
上のアイディアは余裕があるときに試すことにする。
なので、いままでどおりの修正方法でとりあえず実装しよう。
