### ISSUE TITLE
ボタンは丸いアイコンで表示し、マウスオーバーしたときに文字を表示させるようにしたい

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#26]
ボタン（更新ボタンや印刷ボタンなど）を丸いアイコンで表示しておき、マウスオーバーしたときに文字を表示させる。
現時点で実装するよりも後々まとめて修正したほうが良さげなので、一旦保留にしておいた方が良いかも？
![image](https://user-images.githubusercontent.com/77572073/139186789-02cf0185-966e-4309-a4d2-665b72ce08de.png)
![image](https://user-images.githubusercontent.com/77572073/139187630-23a8863b-2279-481c-a75f-1b66f75b1962.png)

**Comment by gamasenninn** [comment]
とりあえず、これで代替えしてみよう。
問題なければこのコードでいきたい

```
  <b-button pill variant="primary" id="btnAdd">+</b-button>
  <b-tooltip target="btnAdd" title="新規作成"></b-tooltip>
```

**Comment by monomonosu** [comment]
請求書ページに適用した。そのその仕様で問題なければ全ページに適用する。

**Comment by monomonosu** [comment]
やはりホバー時のテキスト表示はしなくて良いとの事なので、Closeとする。

**Comment by monomonosu** [comment]
デザイン指摘箇所修正。全体に適用。 #262
