### ISSUE TITLE
タブレットでMWモードのときウィンドウを指でドラッグ移動できない。　優先度:低

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/soho-caddie#375]
これは仕様なのかな。調査する。PCでマウス操作はもちろんOK!
タブレットでMW使う人はほぼ皆無だと思うが、やはり指でドラッグ移動できたほうがいい。

**Comment by monomonosu** [comment]
我スマホで試したが、問題なくドラッグできた

**Comment by gamasenninn** [comment]
タブレットででたとのことで、クローズする。
