### ISSUE TITLE
[請求書]アップロードは商品ごとにできるように。画像やPDFをポップアップで表示したい。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#38]
- 商品名とアップロードしたファイルは関連付けがわかるような形にしたい。
   - 関連付けするとなると、商品項目ひとつひとつにアップロードボタンを設ける必要がある。
   - アップロードしたファイルは文字で表示
   - ファイル名をクリックすると画像やPDFがポップアップなどして表示されるようにしたい。
- アップロード画面は表示・非表示を切り替えられる

詳細は仕様の「請求書アップロード機能(新規・更新)」を参照
https://docs.google.com/presentation/d/1pBjH0iX9WRynZgtLNW-ogVAoUOxu8_12jhBlK_NDUR4/edit#slide=id.gfcfa62ae1a_0_0

- [x] 商品
- [x] 請求
- [x] 見積

**Comment by gamasenninn** [comment]
ローカルで試験する場合はCORS制御が必要になる。
main.py にCORS制御のロジックを追加し
pip install flask_cors
するとうまくいった。

**Comment by monomonosu** [comment]
請求書への商品画像・PDFのアップロード機能の仕様が少し変更になった。
スライドを参照：https://docs.google.com/presentation/d/1pBjH0iX9WRynZgtLNW-ogVAoUOxu8_12jhBlK_NDUR4/edit#slide=id.gfcfa62ae1a_0_0
