### ISSUE TITLE
設定ページのレイアウト修正

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#401]
設定ページのリンクボタンをフッターに入れる。
しかしレスポンシブ的に入りきらない可能性があるので何かしら対策しないとかも。
「CSVエクスポート」「CSVインポート」「DB初期化」ボタンは管理者側の機能なのでフッターに含めなくても良いとの事。

![image](https://user-images.githubusercontent.com/77572073/153977283-41fa1a82-e820-4a0b-8d3f-b0e0faa78ccb.png)

**Comment by gamasenninn** [comment]
レスポンシブ的にはスマホならアイコンにするとかだね。
あとは適用ボタンから距離を離したほうがいいね。
