### ISSUE TITLE
請求・見積ページ。新規作成後にブラウザの更新をすると保存できない。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#535]
請求・見積の新規作成・更新後はページ遷移せずに留まるように #530

このプルリクで新規作成・更新後はページ遷移せずにページに留まるようになったが、
請求・見積を新規作成→ブラウザの更新→続けて保存（更新）しようとするとエラーが出る。
SQLエラーで、NotNullに値が入ってないよ。という内容のエラーなのだが、値がnullのものはローカルストレージに保存されないのが原因だと思う。

**Comment by monomonosu** [comment]
どうやらJSON.stringifyをすると、valueがnullの項目は消されてしまうようだ

**Comment by gamasenninn** [comment]
isPaidをディフォルトFalseにすれば更新されると思うのだが。NotNull項目を登録するときは、かならずディフォルト指定する必要があると思う。

**Comment by gamasenninn** [comment]
↑これ、ちょっとズレた指摘だった。気にしないでね。
