### ISSUE TITLE
領収書:　代表名の役職、但し書きはどうするか？いまはDBに存在しない。

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/soho-caddie#557]
ついでに、領収番号は請求番号でいいのか？
いまは、暫定的に請求番号を入れている。

**Comment by monomonosu** [comment]
- 役職は特に必要無いと思うとの事。
- 但し書きは確かに変えれるようにした方が良いとの事。SohoLifeでは印刷時に自由に入力できるようになっていて、デフォルトでは件名が入るようになっている。
- 領収番号は請求番号と同じで問題ない。

**Comment by gamasenninn** [comment]
では、現状次のようにする。
①但し書きは件名とする。
（現時点では印刷時の入力は対応しない）
②領収番号は請求番号と同じ。
③役職名欄は削除。
