### ISSUE TITLE
備忘:アップロード機能について

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/soho-caddie#56]
●選択削除ができるようにしたい。
●画面拡大はlightboxかな
●変換不能なファイルのサムネイルはイラスト。ファイル名？
●mime見て振り分けるか・・・・

**Comment by monomonosu** [comment]
アップロード機能には画像(.jpgや.png)、PDF、CAD図形(.jww)のプレビュー機能を設けて欲しいようだ。
Word、Excelのプレビューはいらないみたい。

**Comment by gamasenninn** [comment]
了解。PDFはまだ作ってないが、なんとかなりそうだ。JWCADのプレビューに関しては未調査。たぶん、時間がかかる。
