### ISSUE TITLE
見積書でも納品書、領収書の印刷ボタンは必要か？

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/soho-caddie#560]
一般的に見積段階では請求が発生していないのだがら、納品書、領収書の印刷はしない（というかできたらおかしい）。混乱の元になるので、とったほうがいいと思う。

**Comment by monomonosu** [comment]
うん、その通りなので見積ページには納品・領収書印刷機能はいらないとの事だ。
Issue立ててボタン削除しちゃうな
