### ISSUE TITLE
請求・見積ページ。新規作成後にブラウザの更新をすると請求・見積Noが消える。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#565]
請求・見積ページ。新規作成後にブラウザの更新をすると保存できない。 #535
で、新規作成後にブラウザ更新すると保存できないバグは潰せたのだが、保存すると請求・見積Noが消えてしまうバグが発生した。
DB内を見るとapplyNumberがnullになってしまっているようだ。

**Comment by gamasenninn** [comment]
新規作成でDBに登録されたとき、再読み込みしないとNoが取得できないからそうなるよね。
