### ISSUE TITLE
請求書のファイルアップロード機能のレイアウト変更。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#591]
請求書ページのファイルアップロード欄は、上部では無く下の方に幅いっぱいに表示して欲しいそうだ。
~~そして、アップロードしたファイルが1件もない場合は、ドロップエリアを表した「＋」が書かれた項目を表示して欲しいとの事。~~
仕様変更。幅の狭いドロップエリアを設けるだけでOKとの事だ。

![image](https://user-images.githubusercontent.com/77572073/156182964-6f02f853-a1ab-4a4e-8dec-e6a0ad2b9809.png)

**Comment by gamasenninn** [comment]
下部に持ってくるのは大賛成だが、ファイル指定のインプットボックスはbootstrapVueのFILEを使っているので希望どおりのレイアウトにならないと思う。もし、それをする場合、いまのところアップロードライブラリーを自作するしかない。

**Comment by monomonosu** [comment]
やっぱそうだよなぁ...
大平さんに再度聞いてみる

**Comment by gamasenninn** [comment]
とりあえず下部にもっていくのだけやろう。

**Comment by gamasenninn** [comment]
了解。この仕様で実装する。

**Comment by monomonosu** [comment]
すまぬ、若干違うようで、やはりドロップエリアはこんな感じにして欲しいとの事。

![image](https://user-images.githubusercontent.com/77572073/156498517-652a4739-411d-431f-bfbe-afe5450e9f42.png)

**Comment by monomonosu** [comment]
もしドロップエリアで上記レイアウトが厳しければクリック→ファイル選択の方式で構わないとの事。
