### ISSUE TITLE
未更新データ保存モーダル外をクリックするとモーダルが閉じてしまう

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#594]
商品や請求書を入力途中に「＜」で戻る際に表示される未更新モーダル外をクリックするとモーダルが閉じる。
モーダルの仕様なのでバグでは無いが、どちらが選択されたかわからず、混乱の元になるとの事なので修正する。
画面外クリックでモーダルが閉じないようにするか、それが無理そうなら画面外クリック時にどちらが選択されたかわかるようにして欲しいとの事。

![image](https://user-images.githubusercontent.com/77572073/156088112-b09d2c37-2921-4d09-a8d2-fe07cc5ca07b.png)

**Comment by gamasenninn** [comment]
外側を選択しても無反応にしてしまえばいいのではないかな。

**Comment by gamasenninn** [comment]
no-close-on-backdropを指定するとよい。
ちなみにESCキーの禁止は、no-close-on-esc

<b-modal ............. no-close-on-backdrop no-close-on-esc>
