### ISSUE TITLE
添付ファイルがあるかわかる機能を付ける

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#598]
現状、新規・更新画面を開かないと添付ファイルがあるかわからない状態だが、
一覧画面で添付ファイルがわかる機能を付けて欲しいとの事。
下図のような感じ

![image](https://user-images.githubusercontent.com/77572073/156091568-2afd121b-17f1-44c9-908b-8f82084a8825.png)

**Comment by gamasenninn** [comment]
やはりそうきたか。予想していたんだが。
これをやるには、２つの方法がある。
①一覧表示のタイミングで該当するフォルダーを見に行って件数が一つでもあればフラグON。
②アップロードしたタイミングで添付があるかどうかのフラグをDB更新


①の場合はLazyで遅延読み込み反映するとよい。ファイルが大量にある場合、サーバーに負荷がかかる。
②の場合は①の欠点はないが、DB変更する必要がある。

意見を求む

**Comment by monomonosu** [comment]
この機能実装して欲しいと聞いた時にとっさに思ったのは②だな。
負荷的にも②の方が安心だし、②の方が良いと思う。

**Comment by gamasenninn** [comment]
了解。②でいこう。DBのカラム追加。添付ファイルの数。numberOfFilesカラムの追加よろしく。デフォルト値はゼロとする。ゼロなら一覧には非表示。ゼロでなければ添付ありアイコンを表示。できれば、その数もアイコンの横に表示。という仕様にしようか。

**Comment by monomonosu** [comment]
numberOfAttachmentsカラムをItems,Invoices,Quotationsモデルに追加した。
