### ISSUE TITLE
請求・見積書の商品一覧。削除は保存ボタンで適用されるように。

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#617]
請求・見積の商品一覧で商品を削除できてしまうが、これを「保存」を押したら適用されるようにして欲しいとの事。

- [x] 請求書
- [x] 見積書

![image](https://user-images.githubusercontent.com/77572073/156292319-0a859174-9db3-4297-8314-0ad34e83a2db.png)

**Comment by gamasenninn** [comment]
api.pyの300行あたりからのロジック見てもらえればわかると思うが、すでにdeleteは織り込み済なんよ。渡されたjsonデータの中にisDeleteがあるかどうかを判断してdelete_listに登録してあげればよいだけになっている。ちなみにいまはidがあるかどうかだけで、insertかupdateかを振り分けているだけだが、この判断部分にisDeleteフラグの判定を入れてやればよいと思う。

    if data.get('invoice_items'):
        update_list = []
        insert_list = []
        delete_in_list = []
        for item in data['invoice_items']:
            if 'createdAt' in item:
                del(item['createdAt'])
            if 'updatedAt' in item:
                del(item['updatedAt'])

            if item.get('id'):
                update_list.append(item)
            else:
                insert_list.append(item)

        db.session.bulk_update_mappings(Invoice_Item, update_list)
        db.session.bulk_insert_mappings(Invoice_Item, insert_list)
        db.session.query(Invoice_Item).filter(Invoice_Item.id.in_(
            delete_in_list)).delete(synchronize_session='fetch')
