### ISSUE TITLE
APIの設計とモック及びAPI実装にswaggerを使うことにする。

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/soho-caddie#63]
connexionを使う。
手始めにDBに関係ないだろうアップロード機能のAPIを再実装してみる。
実験がうまくいったら、正式に採用の予定。

**Comment by monomonosu** [comment]
了解

**Comment by gamasenninn** [comment]
では、connexionでいく方向で。これを使えば、Flaskのルーティングを書かなくて済むし、API仕様を変更したらymlを出力してFlaskに食わせれば、いいだけ。API実装がわかりやすく、しかも楽になりそう。システムが重くなるかどうかは実験してみないとわからんけど。

**Comment by gamasenninn** [comment]
connexionは今回は使わない。

仕様がかたまった段階でswaggerでAPI仕様を書くとして、このISSUEはいったん閉じる。
