### ISSUE TITLE
検索機能はボタン押下後に行う

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#682]
ほぼすべてのページに適用されている検索機能は、filterを使って入力欄への入力毎に検索を行っているが、これはマシンに負荷がかかりすぎるので廃止。
入力欄にワード入力→検索ボタン押下後にAPIを叩くように変更する。

**Comment by gamasenninn** [comment]
いまの時点ではまずボタンクリックでフィルターがかかるようにする。
フィルター条件が固まった時点でAPI連携を実験しながら実装しよう。
