### ISSUE TITLE
商品に仕入れ先欄が必要

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#694]
商品には仕入先項目が必要らしい。

- [x] Itemsに仕入先カラム追加
- [x] フロント側に仕入先入力欄追加

**Comment by gamasenninn** [comment]
やっぱそうなるか。あったほうがよいとは思っていた。仕入先が複数ある商品の場合。どうするかが問題。初回リリースでは商品マスターに入れる仕入先は一つに限定しよう。

**Comment by monomonosu** [comment]
そうだな
