### ISSUE TITLE
納品書と領収書は合体させる？

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#695]
とあるアプリでは納品書と領収書を合体させた「納品領収書？」を発行するアプリがあるらしい。
現状、納品書と領収書は別々で発行できるようにしているが、現状と同じ２つ別々に発行できる形を取るか、納品領収書だけを発行できる形にするか、どちらが良いか話し合って欲しいとの事。

俺自身は領収書の発行のみ行えれば良いタイプの人間なので、現状と同じ２つ別々で発行できる形の方が良いとは思っているが、親父的にはどうだろうか？

**Comment by gamasenninn** [comment]
うーむ。納品書と領収書を合体とは、あんまり聞かないな。請求書と領収書を合体させるのはよくある。
むしろ、領収書だけ発行してくれ、という場合と
請求書と領収書をお願いします。という場合とに分かれると思う。
最小機能（VIP）として考えた場合、別々のほうがわかりやすい。というのがワシの意見。
もし、合体させるのなら、オプション機能として最初はかくしておいたほうがよいだろう。

いずれにしても、初回のリリースは今の別々でいったほうがよいだろう。
