### ISSUE TITLE
請求・見積・納品・領収書の印刷レイアウト修正（フッター）

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#709]
請求・見積・納品・領収書の印刷レイアウトは以下のように修正する

- 印鑑欄はいらない
- 備考は図２のように表示する

図１

![image](https://user-images.githubusercontent.com/77572073/157157805-82151ba3-ccaa-4c10-b2fe-03493577ee74.png)

図２

![image](https://user-images.githubusercontent.com/77572073/157157965-a591ad3f-cef5-4b82-af8b-43537178d471.png)

**Comment by gamasenninn** [comment]
振込先とかDBにないけどどうする？

**Comment by monomonosu** [comment]
そうだな。それについて聞いてみる。
