### ISSUE TITLE
アップロード機能は保存時のみアップロードする事は可能か

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#726]
請求・見積・商品ページのアップロード機能はファイルをアップロードした後に保存を押さなくてもディレクトリに勝手に保存される。
これを、保存ボタンを押したときのみディレクトリに保存するようにできるだろうか。
もし無理そうなら今のままでも大丈夫との事。

**Comment by gamasenninn** [comment]
ハードル高いが検討してみる。ちょっと時間かかる。
いまあるアイディアとしては、まずはキューイングだけ行って保存ボタンが押されたら、キューイングしたデータをサーバに送信、保存するという流れ。ただその場合ファイル容量が大きい場合はアップロードに時間がかかって保存処理がなかなか終わらないという事案が発生する可能性がある。そうなるとなかなか保存ができないとヤケを起こしたユーザが画面を強制終了させるなんてことも考えられる。
いまの仕様にしたのはなるべく、ファイルはひとつずつ確実に処理させて、処理が終わったものは確実に保存完了しているという実感をもたらすためだ。
実は一括アップロードもあまりさせたくはない。通常のファイルなら問題ないが、イラレ・フォトショのファイルや音声ファイル、動画ファイル、CADデータなどめちゃ重いものも想定される。そうなると、10分も20分も保存のために待たなくてはならなくなる（ようつべのアップロード時間が参考になるだろう）。一個ずつしかも即時保存なら、重い場合はあきらめてリロードしてしまえばよい。
そういう考えで作っているのだが、どう考えるべきかなあ。

**Comment by gamasenninn** [comment]
それと、保存処理自体をキューイングして遅延保存する。という術式も考えられる。イメージ的にはようつべのアップロード術式。ちょうど、雅則がスクリプタんどで作っていた遅延アップロード術式がそれに近い。かなり、ハードル高いが、やってみる価値はあると思うが、リリースまでに間に合うかな？

**Comment by gamasenninn** [comment]
術式としては、ロングポーリングで待つのは呼び側のセッションがなくなったら、迷子になるのであまりよろしくない。したがって処理をキューイングしたらDBで管理する形になるだろう。ただ、サブプロセスは後ろで動いたままになるので、エラー終了でゾンビ化したプロセスがある場合、定期的にお掃除する時間起動プロセスが必要だろう。

**Comment by gamasenninn** [comment]
実は、sinologyはそれやってるんだよね。ユーザにはあまりに簡単にできてしまうのでちっとも難しいことではないと感じるだろうけど、synologyが後ろでやっていることは相当高度のテクニックを駆使しているんだよね。遅延アップロードは、それだけでもリポジトリたてられるぐらいの術式なんだよね。

**Comment by monomonosu** [comment]
んー正直な所まだ修正しないといけない箇所は多いから、これに時間をかけるのもまずいよなぁと思っている。
リリース後に実装する形が現実的かもしれないな

**Comment by gamasenninn** [comment]
あと、ちなみになんだが、別の処理に遷移したり、ブラウザを閉じても遅延アップロードが動いている状態にしなくてはならないとすると、service worker使うことになる。やりたい虫がうずうずするのだが、ハードルは高いな。

**Comment by gamasenninn** [comment]
こういうやりとりに大平さんも参加してもらうとよい。githubのアカウント作ってもらってISSUEも管理してもらおう。

**Comment by monomonosu** [comment]
これは次のフェーズに入ったら実装しようという事になった。

**Comment by monomonosu** [comment]
このIssueをWikiに残し、一旦Closeとする。
