### ISSUE TITLE
消費税率を編集できるようにする

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#768]
今は消費税率１０％固定で請求書や見積書の額を計算しているが、消費税率を編集できるようにする。

**Comment by monomonosu** [comment]
これは過去に作成した請求・見積書に影響が出ないよう、InvoicesとQuotationsにtaxカラムを追加するのがベストだろうか？

**Comment by gamasenninn** [comment]
良い質問だね。まったくそのとおり。
さらにいえば、商品明細ごとに10％と8％を分けられるようにすべきなんだが、そのへんは大平さんの意見が聞きたいところだね。

**Comment by monomonosu** [comment]
商品ごとに消費税率の設定が必要になるし、請求・見積内でも消費税率の設定が必要になり影響範囲のが大きい為、この機能は次フェーズでの実装に回す。

**Comment by monomonosu** [comment]
今フェーズは終了。なのでClose。
次フェーズに持ち越すのでWikiに残す。
