### ISSUE TITLE
商品マルチウィンドウが開けなくなるバグ

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#810]
マルチウィンドウモード時、適当なページ＋設定ページを開いた状態で設定ページのリンクボタンを連打→商品ページを開こうとすると、商品ページが開けなくなる。
ライブラリのバグの可能性もあるし、よほど気が狂わないとリンクボタンを連打するなんてことはしないと思うので、優先度は低め？

![マルチウィンドウバグ](https://user-images.githubusercontent.com/77572073/158195931-2fe1029a-c11c-4a65-9e75-ff1dc54df875.gif)

**Comment by gamasenninn** [comment]
わるい。ワシの環境では再現できん。この現象が発生したときに検証でメッセージがでてないかみてくれるか？

**Comment by gamasenninn** [comment]
サーバ環境で再現できた。検証ツールで見てもエラーは出ていないので、ウィンドウのキューイングロジックにバグがあるかも。見てみる。

**Comment by gamasenninn** [comment]
まあ、潜在バグとして認識しつつ、トリアージ的にはBまたはCかな。

**Comment by monomonosu** [comment]
そうだな
