### ISSUE TITLE
会社ロゴや印鑑のサイズは数値入力で微調整できるように

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#849]
請求・見積・納品・領収書に印字する会社ロゴや印鑑のサイズはユーザーが数値入力等でサイズを微調整できるようにする。
設定ページとかにサイズ入力欄を付ければ良いかもしれない。

**Comment by monomonosu** [comment]
まずはロゴ・印鑑欄に入力欄。カラムの追加。

**Comment by monomonosu** [comment]
とりあえずカラムの追加と入力欄の追加まで行った。

**Comment by gamasenninn** [comment]
OK
あとはPDF出力。こっちでやる。
