### ISSUE TITLE
差分が出た際の保存確認が、項目を編集してなくても出てしまう

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#870]
各種ページの更新画面で項目を編集した状態で一覧ページに戻ろうとすると保存確認モーダルを表示するようにしているが、項目を編集していない状態でもモーダルが表示されてしまうので修正する。

**Comment by gamasenninn** [comment]
これBUGじゃないよ。アップロードしたファイルの数とDB上で管理している論理ファイル数が違うので、この現象がでる。
つまり同期のための保存なんだよね。
テストデータが新規にバッチで作られた場合に起こりやすい。

**Comment by gamasenninn** [comment]
この現象が気持ち悪いという場合、論理ファイル数と物理ファイル数が違った場合はエラーとしない。とすればよいのだが、どうするか？

**Comment by gamasenninn** [comment]
それと、seederを流すとき、アップロード各フォルダの物理ファイル数をカウントして、DBのファイル数を更新するという手もあるな。

**Comment by monomonosu** [comment]
途中でアップロードファイル数を管理するカラムを追加したからそうなっている。という事か。
だとすると対応する必要は無さそうだな。
お客さんに渡す時はすでにカラムは存在してるわけだし。

**Comment by gamasenninn** [comment]
そう。この現象は初期状態とかテスト状態で発生するが、お客さんが故意にアップロードフォルダーにファイルを入れたりすると起きることもある。
なので、この現象については説明書きに書いておけばよいかもしれない。

**Comment by monomonosu** [comment]
了解。
このIssueは仕様って事でCloseするか。

**Comment by monomonosu** [comment]
見積→請求へのコンバート、請求→見積へのコンバートでアップロードファイル数のカラムが引き継がれるからそれを修正する必要はありそうだな。
それが終わり次第完了とする。

**Comment by gamasenninn** [comment]
了解。よろしく。
