### ISSUE TITLE
請求・見積ページの合計金額要素を右揃え

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/soho-caddie#876]
下記画像部分、要素まるまる右揃え

![image](https://user-images.githubusercontent.com/77572073/159121325-86d026b9-eeb6-4379-98ae-d0e9971f6d9c.png)

**Comment by gamasenninn** [comment]
これ♯７９２と関係してるぽいね。もし優先度が高いなら#792に着手してこの問題の解決を探るけどどうする？

**Comment by monomonosu** [comment]
とりあえずこのIssueの通りに右揃えにして、時間があるときにじっくり７９２について検証するというのはどうだろうか

**Comment by gamasenninn** [comment]
了解。
